-- Studio26F Database
CREATE USER studio26f WITH PASSWORD 'studio26f123';
CREATE DATABASE studio26f OWNER studio26f;

\c studio26f;
CREATE TYPE permission AS ENUM ('Banned','Restricted','Normal','Superior','Admin');
CREATE TABLE player (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      text,
    motto         text,
    region        integer,
    avatar        text,
    avatar_hash   text,
    avatar_frame  integer,
    permission    permission,
    password_hash text,
    email         text,
    phone         text
);
ALTER TABLE player OWNER TO studio26f;

-- Techrater Database
CREATE USER techrater WITH PASSWORD 'techrater123';
CREATE DATABASE techrater OWNER techrater;

\c techrater;
CREATE TABLE data (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    statistics  text,
    ranks       text,
    settings    text,
    keymaps     text,
    touch_1     text, touch_2     text, touch_3     text,
    extra_1     text, extra_2     text, extra_3     text
);
ALTER TABLE data OWNER TO techrater;

CREATE TABLE notice (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    create_time timestamp without time zone DEFAULT now(),
    en_us text, zh_cn text, zh_tw text,
    fr_fr text, es_es text, pt_pt text, id_id text, ja_jp text
);
ALTER TABLE notice OWNER TO techrater;
